### ISSUE TITLE
`RefreshingReference.retrieve` should be protected and with parens

### ISSUE THREAD

**Issue by kubukoz** [flowcommerce/lib-play#210]
Since `RefreshingReference`'s `retrieve` method is side-effecting by definition (otherwise there would be no point in caching), it would be better defined as `def retrieve(): T`.
From https://docs.scala-lang.org/style/method-invocation.html:

> this syntax should only be used when the method in question has no side-effects (purely-functional). In other words, it would be acceptable to omit parentheses when calling `queue.size`, but not when calling `println()`

Additionally, calling `retrieve` from the outside doesn't make much sense (unless you want to fetch the data without refreshing the reference - but that would be a really weird usecase, since the reference will eventually be refreshed anyways) - if we're not doing that, I suggest making the method `protected` to avoid accidentally calling it from the outside (although it'll probably break every existing implementation that extends the class directly by requiring it to have an encapsulation modifier at least as strong as `protected`).

Additionally, the constant `maxAttempts = 3` is used twice - I think it's not a controversial idea to have a val for it too :)

**Comment by jlogeart** [comment]
I do not think `retrieve` is side effecting: it is simply the implementation of the function whose result is being cached.

I agree that making `protected` would be a better choice though.

As of `maxAttempts`, the trait is not prescriptive of the actual implementation.

**Comment by kubukoz** [comment]
- about `retrieve` and side effects: I went a bit overboard on the assumption that it's always side-effecting. Indeed, e.g. resource-heavy functions could be used here too.
However, now I realised it's inconsistent with `RefreshingReference.apply` - that function expects a `() => T` function, whereas it could accept a by-name parameter: `=> T`. And to be honest, I have to think about it more to have an opinion on whether both should be of the `() => T` kind :)

- about `maxAttempts` - I just thought that, since it's the default in both ways of creating an instance (inheritance or `RefreshingReference.apply`, it could be defined in a single place.

**Comment by kubukoz** [comment]
The current idea I have is that `retrieve` is potentially side-effecting, so the parens wouldn't hurt - what hurts is having an implementation of the trait that has `def retrieve: T` as the signature and a side-effecting implementation. IMO it's better to assume a function has side effects and discover it doesn't, than assume it's pure and figure out it's not after hours of debugging :P

A parallel-world example: an `IO[Int]` value can be created using `IO { execBlockingIOOperation }` and `IO.pure { 5 }` - one is side effecting and one isn't, but the potential effect is encoded in the type.
